INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Nina Brown', 'nina@gmail.com', '$2a$10$J5vfMZy9n81ez/cvYpkdAeyauHmWTyMUsskPVMolfhiFL450dE4Ta');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Leia Red', 'leia@gmail.com', '$2a$10$J5vfMZy9n81ez/cvYpkdAeyauHmWTyMUsskPVMolfhiFL450dE4Ta');

INSERT INTO TB_ROLE (ROLE_NAME) VALUES ('ROLE_OPERATOR');
INSERT INTO TB_ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2);